<a href="https://apssdc.in"><img src="https://camo.githubusercontent.com/e7501c5948d48f88dad8ab2ab6bd448e1cfd6c79/68747470733a2f2f64726976652e676f6f676c652e636f6d2f75633f6578706f72743d646f776e6c6f61642669643d3135414b51365f2d42697857344b366d4c36525070684635454b58715946327a6a" width="900" align="center"></a>

<h1><center>Data Manipulation with NumPy
</center></h1>
<img src="https://techscript24.com/wp-content/uploads/2020/10/86498201-a8bd8680-bd39-11ea-9d08-66b610a8dc01.png" width="150" align="center">


## Day Objectives

- Introduction
- NumPy Arrays
- NumPy Basics
- Math
- Indexing
- Random
- Filtering
- Statistics
- Aggregation
- Saving Data

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 5, 8, 6, 55])
arr2 = np.array((1, 5, 8, 6, 55))

In [3]:
type(arr), type(arr2)

(numpy.ndarray, numpy.ndarray)

In [4]:
arr.ndim

1

In [5]:
arr.shape

(5,)

In [6]:
arr.dtype

dtype('int32')

In [7]:
arr.size

5

In [8]:
arr.nbytes

20

In [9]:
arr = np.array([1, 5, 8, 6, 55, 'apssdc'])

print(arr)

['1' '5' '8' '6' '55' 'apssdc']


In [10]:
np.array([1, 5, 8, 6, 55, 5.5, 5.6, 8.5, 5 + 3j])

array([ 1. +0.j,  5. +0.j,  8. +0.j,  6. +0.j, 55. +0.j,  5.5+0.j,
        5.6+0.j,  8.5+0.j,  5. +3.j])

In [11]:
np.array([1, 5, 8, 6, 55, 5.2])

array([ 1. ,  5. ,  8. ,  6. , 55. ,  5.2])

In [12]:
arr.dtype

dtype('<U11')

In [15]:
np.append(arr, 5)

array(['1', '5', '8', '6', '55', 'apssdc', '5'], dtype='<U11')

In [16]:
np.array([1, 5, 8, 66, 88, 66], dtype = 'int16')

array([ 1,  5,  8, 66, 88, 66], dtype=int16)

In [17]:
a2 = np.array([[1, 2, 3, 4, 5],
              [1, 3, 6, 9, 6]])

a2

array([[1, 2, 3, 4, 5],
       [1, 3, 6, 9, 6]])

In [18]:
a2.shape

(2, 5)

In [19]:
a2.reshape(5, 2)

array([[1, 2],
       [3, 4],
       [5, 1],
       [3, 6],
       [9, 6]])

In [20]:
a2.reshape(10, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [1],
       [3],
       [6],
       [9],
       [6]])

In [21]:
a2[0]

array([1, 2, 3, 4, 5])

In [22]:
a2[0][0]

1

In [24]:
a1 = np.arange(10, 100, 0.1)

a1.shape

(900,)

In [28]:
a1.reshape(3, 100, 3)

array([[[10. , 10.1, 10.2],
        [10.3, 10.4, 10.5],
        [10.6, 10.7, 10.8],
        [10.9, 11. , 11.1],
        [11.2, 11.3, 11.4],
        [11.5, 11.6, 11.7],
        [11.8, 11.9, 12. ],
        [12.1, 12.2, 12.3],
        [12.4, 12.5, 12.6],
        [12.7, 12.8, 12.9],
        [13. , 13.1, 13.2],
        [13.3, 13.4, 13.5],
        [13.6, 13.7, 13.8],
        [13.9, 14. , 14.1],
        [14.2, 14.3, 14.4],
        [14.5, 14.6, 14.7],
        [14.8, 14.9, 15. ],
        [15.1, 15.2, 15.3],
        [15.4, 15.5, 15.6],
        [15.7, 15.8, 15.9],
        [16. , 16.1, 16.2],
        [16.3, 16.4, 16.5],
        [16.6, 16.7, 16.8],
        [16.9, 17. , 17.1],
        [17.2, 17.3, 17.4],
        [17.5, 17.6, 17.7],
        [17.8, 17.9, 18. ],
        [18.1, 18.2, 18.3],
        [18.4, 18.5, 18.6],
        [18.7, 18.8, 18.9],
        [19. , 19.1, 19.2],
        [19.3, 19.4, 19.5],
        [19.6, 19.7, 19.8],
        [19.9, 20. , 20.1],
        [20.2, 20.3, 20.4],
        [20.5, 20.6,

In [32]:
zero = np.zeros((10, 10), dtype='int8')

zero

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [34]:
one = np.ones((10, 10, 10), dtype='int8')

one

array([[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [36]:
np.full((10,10), 10)

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [38]:
p = np.full((10,10), 'P')

In [39]:
np.full_like(p, 'A')

array([['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
       ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
       ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
       ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
       ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
       ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
       ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
       ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
       ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'],
       ['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A']], dtype='<U1')

In [40]:
[1, 5, 8, 9] + 5

TypeError: can only concatenate list (not "int") to list

In [41]:
one + 5

array([[[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6]],

       [[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6]],

       [[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6, 6, 6, 6, 

In [43]:
x = one + 5.5

In [44]:
x.sum()

6500.0

In [48]:
s = x.cumsum()

In [47]:
x.cumprod()

array([6.50000000e+000, 4.22500000e+001, 2.74625000e+002, 1.78506250e+003,
       1.16029062e+004, 7.54188906e+004, 4.90222789e+005, 3.18644813e+006,
       2.07119128e+007, 1.34627433e+008, 8.75078317e+008, 5.68800906e+009,
       3.69720589e+010, 2.40318383e+011, 1.56206949e+012, 1.01534517e+013,
       6.59974359e+013, 4.28983333e+014, 2.78839167e+015, 1.81245458e+016,
       1.17809548e+017, 7.65762062e+017, 4.97745340e+018, 3.23534471e+019,
       2.10297406e+020, 1.36693314e+021, 8.88506541e+021, 5.77529252e+022,
       3.75394014e+023, 2.44006109e+024, 1.58603971e+025, 1.03092581e+026,
       6.70101776e+026, 4.35566155e+027, 2.83118001e+028, 1.84026700e+029,
       1.19617355e+030, 7.77512809e+030, 5.05383326e+031, 3.28499162e+032,
       2.13524455e+033, 1.38790896e+034, 9.02140823e+034, 5.86391535e+035,
       3.81154498e+036, 2.47750424e+037, 1.61037775e+038, 1.04674554e+039,
       6.80384601e+039, 4.42249990e+040, 2.87462494e+041, 1.86850621e+042,
       1.21452904e+043, 7

In [49]:
s.max()

6500.0

In [50]:
s.min()

6.5

In [51]:
s.argmin()

0

In [52]:
s.argmax()

999

In [53]:
s.mean()

3253.25

In [54]:
s

array([   6.5,   13. ,   19.5,   26. ,   32.5,   39. ,   45.5,   52. ,
         58.5,   65. ,   71.5,   78. ,   84.5,   91. ,   97.5,  104. ,
        110.5,  117. ,  123.5,  130. ,  136.5,  143. ,  149.5,  156. ,
        162.5,  169. ,  175.5,  182. ,  188.5,  195. ,  201.5,  208. ,
        214.5,  221. ,  227.5,  234. ,  240.5,  247. ,  253.5,  260. ,
        266.5,  273. ,  279.5,  286. ,  292.5,  299. ,  305.5,  312. ,
        318.5,  325. ,  331.5,  338. ,  344.5,  351. ,  357.5,  364. ,
        370.5,  377. ,  383.5,  390. ,  396.5,  403. ,  409.5,  416. ,
        422.5,  429. ,  435.5,  442. ,  448.5,  455. ,  461.5,  468. ,
        474.5,  481. ,  487.5,  494. ,  500.5,  507. ,  513.5,  520. ,
        526.5,  533. ,  539.5,  546. ,  552.5,  559. ,  565.5,  572. ,
        578.5,  585. ,  591.5,  598. ,  604.5,  611. ,  617.5,  624. ,
        630.5,  637. ,  643.5,  650. ,  656.5,  663. ,  669.5,  676. ,
        682.5,  689. ,  695.5,  702. ,  708.5,  715. ,  721.5,  728. ,
      

In [55]:
s.dtype

dtype('float64')

In [56]:
s.astype(int)

array([   6,   13,   19,   26,   32,   39,   45,   52,   58,   65,   71,
         78,   84,   91,   97,  104,  110,  117,  123,  130,  136,  143,
        149,  156,  162,  169,  175,  182,  188,  195,  201,  208,  214,
        221,  227,  234,  240,  247,  253,  260,  266,  273,  279,  286,
        292,  299,  305,  312,  318,  325,  331,  338,  344,  351,  357,
        364,  370,  377,  383,  390,  396,  403,  409,  416,  422,  429,
        435,  442,  448,  455,  461,  468,  474,  481,  487,  494,  500,
        507,  513,  520,  526,  533,  539,  546,  552,  559,  565,  572,
        578,  585,  591,  598,  604,  611,  617,  624,  630,  637,  643,
        650,  656,  663,  669,  676,  682,  689,  695,  702,  708,  715,
        721,  728,  734,  741,  747,  754,  760,  767,  773,  780,  786,
        793,  799,  806,  812,  819,  825,  832,  838,  845,  851,  858,
        864,  871,  877,  884,  890,  897,  903,  910,  916,  923,  929,
        936,  942,  949,  955,  962,  968,  975,  9

In [58]:
len(dir(np)), len(dir(arr))

(620, 162)

In [59]:
np.random.rand(50)

array([0.79849964, 0.8788829 , 0.03635635, 0.60797299, 0.97730674,
       0.00715342, 0.47726547, 0.46955013, 0.02401103, 0.87227896,
       0.9286049 , 0.02657484, 0.43874178, 0.44399306, 0.76267586,
       0.96373575, 0.35789011, 0.57371567, 0.84231408, 0.05044925,
       0.21663274, 0.51985749, 0.46819652, 0.50097777, 0.66659776,
       0.44412162, 0.58276018, 0.76603464, 0.4561569 , 0.29728984,
       0.16488672, 0.5843838 , 0.46589783, 0.15788746, 0.22385659,
       0.64501984, 0.95434144, 0.90569448, 0.34937791, 0.41524648,
       0.15820922, 0.94487933, 0.20153189, 0.32161214, 0.32201024,
       0.43621752, 0.99309074, 0.58531417, 0.99543531, 0.81469691])

In [63]:
nor = np.random.normal(loc=5, scale=10, size = 50)

nor

array([ 22.31333364,  -6.84066915, -17.02980766,   3.40049574,
         6.20942941,  19.95765077,  10.82772845,   6.66591538,
         5.67880537,  10.1886478 ,   4.39221516,  18.55089878,
        13.50648949,  25.72852627,   5.04001489,   7.77964113,
         8.83498881,  17.69716967,  17.12178447,  -6.30229977,
         8.29084503,  23.40405001,  -4.3141646 ,   0.50016934,
         6.19993008, -10.10778068,   4.74935233,  -0.38014234,
        -9.67725344,   7.9987713 ,   7.55971994, -12.41822649,
        13.28074932, -19.18402089, -12.32111761,   2.54317514,
       -10.69565543,  -6.05013093,   9.104733  ,  -3.0286153 ,
         0.07733036,   7.03544829,  21.21806509,  10.04827852,
        -8.27341052,  -3.99076335,   1.06062708,  24.71826363,
         0.39629069,  -1.92069955])

In [64]:
nor.mean()

4.390895533598956

In [66]:
nor.std()

10.999207928437755

In [73]:
marks = np.random.randint(30, 100, 100)

In [74]:
marks > 40

array([ True,  True,  True, False,  True, False,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False,  True,  True,  True,  True,  True,
       False])

In [76]:
marks[marks > 40].size

86

In [78]:
marks[(marks > 40) & (marks % 2 == 0)]

array([78, 74, 80, 50, 98, 54, 42, 64, 68, 86, 94, 70, 60, 68, 62, 94, 90,
       72, 78, 74, 42, 76, 42, 80, 64, 86, 90, 78, 72, 54, 44, 62, 52, 52,
       62, 94, 96, 74, 98, 86, 72, 64, 66, 64, 98, 98, 68, 54])

In [79]:
np.var(marks)

409.9675

## CSE

12, 19, 23, 4, 41, 39, 7, 15, 24, 68, 65, 69, 66, 46, 27, 29, 58, 25, 43, 31, 51, L61, 40

## ECE

61, 47, 58, 65, 5, 8, 42, 31, 45, 